### ISSUE TITLE
Naming inconsistency vibr_calibrate_02.cfg

### ISSUE THREAD

**Issue by MartinGiersberg** [Frix-x/klipper-voron-V2#10]
I belive there are some slight inconsistancyies in the Instructions of vibr_calibrate_02.cfg

#   4. Add vibrations_graph.py in the same folder in your config. You can find this file in my scripts folder
#   4bis. Make it executable using SSH: type 'chmod +x ./vibrations_graph.py' when in the folder.

The provided python script in [graph_vibrations.py](https://github.com/Frix-x/klipper-voron-V2/blob/main/scripts] is however called graph_vibrations.py, so just the two words spun arround.

Thanks a lot for you work !!!

**Comment by Frix-x** [comment]
Hey, thank you very much for this higlight ! I'll correct that mistake :)

**Comment by MartinGiersberg** [comment]
You are more than welcome ! Thanks again for developing this tool!
