### ISSUE TITLE
Ease the installation of scripts (Zcalib, ERCF, IS, ...)

### ISSUE THREAD

**Issue by d5aint** [Frix-x/klipper-voron-V2#100]
Can you include the ercf.py script in the scripts folder?
Will need to include instructions as well for others to move it to the klipper/klippy/extra folder.

**Comment by Frix-x** [comment]
This is a good idea.

And this make me think about making all in one install script that would install all the scripts for the IS workflow, vibrations, ERCF, moving all the files, doing the chmod, etc... It would allow an easier install procedure for everything... I need to think about it :)

**Comment by d5aint** [comment]
this is off topic of this issue, but also the auto z-calibration script as well.

**Comment by Frix-x** [comment]
I've changed the issue title to keep track of everything here. It will be easier to not forget that way 😅

**Comment by sebadue** [comment]
Why should that be a good idea? Separately maintained scripts should be individually installed from their GitHub repositories and symlinked to the extras folder. You should be responsible for updating this repo if ercf or z_calib is updated.
Or did I get anything wrong here?

**Comment by Frix-x** [comment]
Oh no no: I don't want to integrate the external scripts here (ERCF & auto Z calibration). I want to do an install script that fetch and download them directly from their respective repositories and do automatically the symlinks (or call their own install scripts).

**Comment by sebadue** [comment]
Ah okay ;) Nevermind, I didn‘t get that.

**Comment by d5aint** [comment]
Correct, would be too much work to constantly be monitoring them for updates.
Just need to make the end user aware that these scripts are required and how to get them.
But a git install would be perfect.
