### ISSUE TITLE
Revamp vibr_calibrate_0x.cfg

### ISSUE THREAD

**Issue by elpopo-eng** [Frix-x/klipper-voron-V2#105]
is it possible to rename/revamp vibr_calibrate file because I find it not very explicit ?
We can do something like that : 
vibr_calibrate_01.cfg -> shapper_calibration.cfg
vibr_calibrate_02.cfg -> axis_vibration_measurement.cfg

**Comment by Frix-x** [comment]
Yes, this can be done easily in the v3
