### ISSUE TITLE
Mellow Fly-sb2040 CANboard support

### ISSUE THREAD

**Issue by fsaad1984** [Frix-x/klipper-voron-V2#112]
This CANboard is pretty popular and used by many in the community. It would be nice to have this mcu added to the config/mcu folder.

pinout information can be found here: https://mellow.klipper.cn/#/board/fly_sb2040/pins

**Comment by Frix-x** [comment]
Thanks,

I'll add it as well. If you want to do a PR about that, I'll be happy to accept it :)

**Comment by wtsexton** [comment]
Here is the configuration I use for one I recently installed.

```
[mcu toolhead]
##--------------------------------------------------------------------
canbus_uuid:  b245dace1fa4
##--------------------------------------------------------------------


[board_pins mcu_sb2040]
mcu: toolhead
aliases:
# steppers
   E_STEP=gpio9,  E_DIR=gpio10,  E_ENABLE=gpio7,  E_TMCUART=gpio8,
   X_STOP=gpio29,
# hotend
   E_HEATER=gpio6, E_TEMPERATURE=gpio27, E_FAN=gpio14,
   PART_FAN=gpio13,
# probe
   PROBE_INPUT=gpio28,
# light
   STATUS_NEOPIXEL=gpio12,
# adxl
   ADXL_CS=gpio1, ADXL_SCLK=gpio0, ADXL_MOSI=gpio3, ADXL_MISO=gpio2

```

**Comment by Frix-x** [comment]
Thanks for the pinout :)

**Comment by fsaad1984** [comment]
Hi @flatbrotato, thanks for your comment. This config is indeed similar to what I use. I also defined the chamber temp sensor although this gives an inaccurate reading due to the sensor's placement:

# chamber
    CHAMBER_TEMPERATURE=gpio26

I am not super confident in how to push a PR, so feel free to do so if you want.

**Comment by flatbrotato** [comment]
> Hi @flatbrotato, thanks for your comment. This config is indeed similar to what I use. I also defined the chamber temp sensor although this gives an inaccurate reading due to the sensor's placement:
> 
> ```
> # chamber
>     CHAMBER_TEMPERATURE=gpio26
> ```
> 
> I am not super confident in how to push a PR, so feel free to do so if you want.

I did the same, however I defined it else where so I can see it.

```
[temperature_sensor Toolhead_Chamber]
sensor_type = ATC Semitec 104GT-2
sensor_pin = toolhead:gpio26
```

**Comment by Frix-x** [comment]
This is done in commit https://github.com/Frix-x/klipper-voron-V2/pull/104/commits/058469ef3ad29324aa1d2716f1e0b9d281e8a4ce :)
