### ISSUE TITLE
Missing 's' in filename

### ISSUE THREAD

**Issue by d5aint** [Frix-x/klipper-voron-V2#12]
In files vibr_calibrate_01.cfg and vibr_calibrate_02.cfg, the 's' is missing at the end of the file name for making it executable.
 
3. Add plot_graphs.sh somewhere in your config. You can find this file in my scripts folder
#   3bis. Make it executable using SSH: type 'chmod +x ./plot_graph.sh' when in the folder

Otherwise, worked perfect.
Was able to make my machine run a little quieter.
Thanks for spending the time to build this.

**Comment by Frix-x** [comment]
Thanks for the hint ! I'll correct it quickly :)
