### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Frix-x** [Frix-x/klipper-voron-V2#17]
Now that the config is becoming more generic and used as is by multiple people (at least elpopo and me) on multiple machines (at least Voron V2.4 machines and also a TriZero machine), the REAME need to be improved to become more focused on global install instructions

**Comment by d5aint** [comment]
Let me know what I can do to assist.
With the changes recently made, this is becoming an excellent config.

**Comment by Frix-x** [comment]
Thank you for the proposal ! I was on holiday for a couple of days and will be back to it next week :)

So I'll rework the main README.md file to make it more generic and not focused only on "my machine". The goal is to describe the config tree, how to install it, what are the features, how to customize it and to adapt it to another machine. In the meantime, if you want to do a PR with a draft, feel free to do it :)

**Comment by d5aint** [comment]
Thanks. will do that.
