### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by ShryuKt** [Frix-x/klipper-voron-V2#41]
Hello,

You have a little typo in graph_vibrations.py
```# Be sure to make this script executable using SSH: type 'chmod +x ./graph_vibrations.sh' when in the folder !```
It should be ".py" not ".sh"
```# Be sure to make this script executable using SSH: type 'chmod +x ./graph_vibrations.py' when in the folder !```

**Comment by Frix-x** [comment]
Thanks for raising that issue !

I'm currently rewriting all the documentation, so it will be corrected in the next version :)

**Comment by sharmadhiraj86** [comment]
I have fixed the issue can you please take a look and let me know if there is anything else to be done.
