### ISSUE TITLE
Limit acceleration in homing QGL etc.

### ISSUE THREAD

**Issue by elpopo-eng** [Frix-x/klipper-voron-V2#42]
I have configured an high Accel for my 2.4 (max accel 30k) and this disturbs homing and qgl.
So I propose to add a variable in variable.cfg to limit accel in those macro, something like `accel_during_homing_tilt`

**Comment by Frix-x** [comment]
Ok for me ! I'll keep the feature on hold until the new version is merged and then I'll add it
