### ISSUE TITLE
Vibrations macros  does not works on newly installed Moonraker 

### ISSUE THREAD

**Issue by fbeauKmi** [Frix-x/klipper-voron-V2#45]
Hey,
As Moonraker changes files structures, the vibration macros does not work anymore on newly installed printer.

The shell command and plot_graphs.sh,  where pathes are hardcoded, irremediably yield to error. 

One way could be to convert all config to the new structure, another one to add symbolic links in the documentation. 

What do you think about it?

**Comment by Frix-x** [comment]
Hello, thanks for raising an issue.

This is already in my to do list for the new config release. I plan to release it with a rework of this section to make it compatible with the new moonraker requirements (ie. change the paths and/or see how to be more flexible).

**Comment by fbeauKmi** [comment]
Nice, I also identify an issue when user is not "pi". As it can be done writing Raspian Image, it could be a great improvement to tkae it in account.

**Comment by Frix-x** [comment]
Yes this is already managed by the graph_vibrations.py script as you can add a `-k /home/xxxx/klipper_config` parameter to set the correct path for the script. It's the only place where the user name can be a problem. I agree though that it's not straightforward to use...

I definitely need to do something on this topic !
