### ISSUE TITLE
Home Y before X

### ISSUE THREAD

**Issue by shlagwuk** [Frix-x/klipper-voron-V2#47]
With Klicky, you can chose what axe to home first.
With an EBB36 can you home Y first, back away a few centimeters and home X, so the EBB doesn't crash in the Z chain.

See klicky_variables.cfg below:
`variable_home_backoff_x:        10    # how many mm to move away from the X endstop after homing X
variable_home_backoff_y:        20    # how many mm to move away from the Y endstop after homing Y
variable_override_homing:       'Y'    # configures what axis to home first`

Would it be possible with your macros ?

**Comment by Frix-x** [comment]
Yes, this is a good point that I'll add to the config !
