### ISSUE TITLE
horizontal_move_z can't be less than probe's z_offset

### ISSUE THREAD

**Issue by kwijibo12** [Frix-x/klipper-voron-V2#63]
Hi there,

I followed the youtube guide and i get this message. Im using the klicky probe. Any idea why i am getting this message? This happens after the printer does the z_calibrate and tries to run the bed mesh and mesh points are being loaded.

Thanks

**Comment by Tom-T** [comment]
@kwijibo12 I'm having the same issue. What was the resolution?

**Comment by Tom-T** [comment]
I just gave probe z offset a higher value and that worked!
