### ISSUE TITLE
Relocating STATUS_LEDS to the initial Macro

### ISSUE THREAD

**Issue by W141-ID** [Frix-x/klipper-voron-V2#66]
At the Moment it is placed at START_PRINT. Resulting in changing the light only when printing.

Moving the STATUS_LEDS call to the macro will result in changing lights everytime the macro is called.

**Comment by Frix-x** [comment]
This is a good idea and I'll definitely do it :)

**Comment by W141-ID** [comment]
> This is a good idea and I'll definitely do it :)

I have done a push including the needed changes. Feel free to comment on that.

**Comment by Frix-x** [comment]
Hello,

Since I've merged #77 now. Can you do the LEDs PR again ? I still think it's a good addition to this config to make it more clean :)

Tell me if it's ok for you or I'll do it myself in the next couple of days

**Comment by W141-ID** [comment]
Yes just waited for the merge. Will pr soon need to make some changes.

**Comment by Frix-x** [comment]
Ok, I tested the PR #90 and everything is OK. I'll merge it and I think we can close this one :)
