### ISSUE TITLE
ERCF in pause and start_print.cfg

### ISSUE THREAD

**Issue by Benoitone** [Frix-x/klipper-voron-V2#76]
if an error loading error of the ercf occurs during print_start, the macro continues to run and the pause is only made when printing start...

**Comment by Frix-x** [comment]
Hello,

As I don't have an ERCF myself at the moment it's quite hard for me to work on that now.
However, @elpopo-eng, do you have any insights about this issue ?

**Comment by Benoitone** [comment]
my temporary solution is to use the toolhead sensor to stop the macro in case of non detection of filament at the end of loading
