### ISSUE TITLE
include static frequency generator macro/script

### ISSUE THREAD

**Issue by EricZimmerman** [Frix-x/klipper-voron-V2#79]
something like this:

https://gist.github.com/EricZimmerman/d6bf8a4b0a200611f3d9aa308a31e3c1

to allow for telling the printer to vibrate at 87 hz for troubleshooting based on output graphs

**Comment by Frix-x** [comment]
Hello,

Thank you for raising an issue about that. As discussed on the Voron Discord, I will be happy to add support for this. I just need to find some time to do it properly, but it's on my TODO list :)
