### ISSUE TITLE
Update process

### ISSUE THREAD

**Issue by shlagwuk** [Frix-x/klipper-voron-V2#80]
Hi,

Can you add an update process in your README.md ?
For instance, If I want to update to your last macros but keep my changes (printer.cfg, pinout etc), how should I do ?

Thanks!

**Comment by yanfoo** [comment]
Being on Github you can clone this repo and work on your own. You can then compare his files when they are updated to your cloned repo this will not "commit" anything to his files but just on your own github files.

I used to do it this way with the github desktop app and honestly I find it faster to just edit the few files by hand.

**Comment by Frix-x** [comment]
Yes, the magic of Git should allow an easy update while keeping your locally modified files. However, I agree that for Git beginners, it's not as straightforward.

So I'll add some documentation about it in the README :)

**Comment by d5aint** [comment]
What you can do as well is open both files in notepad++ and compare the two.

**Comment by shlagwuk** [comment]
> What you can do as well is open both files in notepad++ and compare the two.

Well yes, but that doesn't seem like the best way to use Git ;-)

I will manually upgrade to the last version and check my files one by one this time, and figure how to do it with git for the next commit!
