### ISSUE TITLE
Lastest Klipper update breaks flow test

### ISSUE THREAD

**Issue by TravisWilder** [Frix-x/klipper-voron-V2#84]
https://github.com/Klipper3d/klipper/commit/0c5c87d7c08c2b8aa2f248d81dd1003c5c7d5a7c

WIth the latest update Klipper will not work with the current Flow test and will stop on the G2/G3 commands

**Comment by Frix-x** [comment]
Thanks for the hint. I'll correct that ASAP :)

**Comment by fbeauKmi** [comment]
Don't be too prompt to fix that, there's probably a bug in this commit. When J or I = 0 its returns error missing coords. At least on my system :/

**Comment by Frix-x** [comment]
This is discussed here : https://github.com/Klipper3d/klipper/pull/5937

**Comment by fbeauKmi** [comment]
Fixed by this one https://github.com/Klipper3d/klipper/pull/5939 tested last night.  It's OK

**Comment by Frix-x** [comment]
@fbeauKmi so I can close the issue ? Or is there some modifications to do on my macro ?
I still did not have time to update Klipper on my side but I'll do it next week if needed.

**Comment by ShryuKt** [comment]
I think you can close, I tested your macro since the new klipper update and it's OK on my side.

**Comment by fbeauKmi** [comment]
Hi, 
Nothing to change to your macros. Gcode_arcs behaves as it should since the last PR. You can close this one.

**Comment by Frix-x** [comment]
Ok, thanks !
I'll close it now :)
