### ISSUE TITLE
Disable filament_motion_sensor during filament macros

### ISSUE THREAD

**Issue by fbeauKmi** [Frix-x/klipper-voron-V2#88]
Hi,
This one  is just to remember to deactivate the optional filament_motion_sensor during the macros relating to the filament in :
- [/macros/helpers/filament_swap.cfg](https://github.com/Frix-x/klipper-voron-V2/blob/main/macros/helpers/filament_swap.cfg)
- [/macros/helpers/nozzle_cleaning.cfg](https://github.com/Frix-x/klipper-voron-V2/blob/main/macros/helpers/nozzle_cleaning.cfg)

Seems to be good practice. Thanks

**Comment by Frix-x** [comment]
Hey thanks for the suggestion. This will be added in a following PR :)
