### ISSUE TITLE
Wrong PA calculation

### ISSUE THREAD

**Issue by Fragmon** [Frix-x/klipper-voron-V2#91]
https://github.com/Frix-x/klipper-voron-V2/blob/29c1fe63340ce30607c622cdb6c256665869c128/macros/calibration/calibrate_pa.cfg#L128

The calculation is wrong. You should use this:

{action_respond_info("PA of the last band: %.4f" % (pa_start + ((num_bands - 1) * pa_increment)))}

**Comment by Frix-x** [comment]
Thanks, you're right. This will be corrected in a following PR :)
