### ISSUE TITLE
macro pause_resume.cfg....restore_gcode_state move_speed should be mm/sec not mm/min

### ISSUE THREAD

**Issue by nigelpjames** [Frix-x/klipper-voron-V2#95]
Hi, Shouldn't move_speed for restore_gcode_state be specified in mm/s rather than mm/min in your pause_resume.cfg macro? e.g.

{% set St = printer["gcode_macro _USER_VARIABLES"].travel_speed  %}

Vs

{% set St = printer["gcode_macro _USER_VARIABLES"].travel_speed * 60 %}
RESTORE_GCODE_STATE NAME=PAUSE_state MOVE=1 MOVE_SPEED={St}

BTW - Really appreciate your adaptive mesh macros

**Comment by Frix-x** [comment]
Hey, thanks for raising an issue. You're right it's a mistake :)

I'll correct it in a following PR in a couple of minutes :)
