### ISSUE TITLE
Add mcu temp

### ISSUE THREAD

**Issue by D1rect10ns** [Frix-x/klipper-voron-V2#99]
This should work with with any mcu with an STM cpu. In printer.cfg add the following include to the 'Other temperature sensors configuration' section:

`[include config/hardware/temperature_sensors/mcu_temp.cfg]`

Create the mcu_temp.cfg in the above location, containing the following code:

```
[temperature_sensor mcu]
sensor_type = temperature_mcu
min_temp =    0
max_temp =    90
```

**Comment by Frix-x** [comment]
Thanks for this suggestion. If you want to do a PR about this, I'll be happy to accept it :)
